---
title: "Plots for 19andMe blogpost"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(lubridate)
library(cowplot)
library(latex2exp)
extrafont::loadfonts(device = "win",  quiet = TRUE)

dat <- read_csv(file.path("..","Data","usafacts_021921.csv"))

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
ggplot_cols <- gg_color_hue(5)
```

## CFR over time by state
```{r}
d_plot_state <- dat %>% 
  group_by(state, date) %>% summarise(cases=sum(cases), deaths=sum(deaths)) %>%
  group_by(state) %>% arrange(date) %>%
  mutate(CFR = (deaths - lag(deaths, 90)) / (lag(cases,13)-lag(cases,103))) %>% ungroup()

max_states <- d_plot_state %>% filter(date==max(date)) %>% arrange(rank(-1*cases)) %>% 
  pull(state) %>% .[1:5]

d_plot_nat <- dat %>% 
  group_by(date) %>% summarise(cases=sum(cases), deaths=sum(deaths)) %>%
  arrange(date) %>%
  mutate(CFR = (deaths - lag(deaths, 90)) / (lag(cases,13)-lag(cases,103)),
         state ="USA") %>% ungroup()

d_plot <- bind_rows(d_plot_state, d_plot_nat) %>% 
  filter(state %in% max_states | state=="USA") %>% 
  na.omit() %>%
  mutate(state=fct_relevel(state,"USA"))

lab_pos <- 
  filter(d_plot, date==min(date)) %>%
  arrange(desc(CFR)) %>%
  mutate(lab_pos = CFR + c(.002,.002,-.006,0,.002,-.002))
  
p1 <- d_plot %>% 
  ggplot(aes(x=date, y=CFR, color=state, linetype=state)) +
  geom_line() + 
  geom_label(data=lab_pos, 
             aes(x=date-15, y=lab_pos, label=state), 
             show.legend=F, direction="y", size=2) +
  
  geom_segment(y = 0.0138, yend = 0.0138, 
               x = min(d_plot$date), xend = ymd("2020-11-01"),
               color="red", linetype="dotted") +
  geom_segment(y = 0.006, yend = 0.006, 
               xend = max(d_plot$date), x = ymd("2020-10-01"),
               color="blue", linetype="dotted") +
  geom_text(label = TeX("March 2020 IFR estimate: $1.38%^{17}$"),
            data = lab_pos[1,], aes(x = date),  y = 0.0138, color = "red",
            hjust=0, vjust = 1.5, size=2) +
  geom_text(label = TeX("November 2020 IFR estimate: $0.6%^{33}$"),
            data = lab_pos[1,], aes(x = max(d_plot$date)),  y = 0.006, color = "blue",
            hjust=1, vjust = 1.5, size=2) +
  
  scale_x_date("",date_breaks = "1 month", date_labels =  "%b %Y") +
  scale_y_continuous("90-day case fatality rate",
                     lim = c(0,.1), labels=scales::percent) +
  ggthemes::scale_color_colorblind() +
  scale_linetype_manual("", values = c("dashed", rep("solid", 5))) +
  labs(color="") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=12),
        legend.position = "bottom",
        legend.margin=margin(t=-20)) +
  guides(color=guide_legend(ncol=6)) +
  ggtitle("a) Case fatality rate over time")

p1
```

## UR by state on Feb 18, 2021
```{r}
bind_rows(d_plot_state, d_plot_nat) %>%
  filter(date==max(date)) %>%
  mutate(UR = CFR/.006) %>%
  filter(UR == min(UR) | UR==max(UR) | state=="USA")
```

## Reported versus adjusted cases
```{r, fig.width=6, fig.height=3.5}
d_plot <- dat %>% 
  group_by(date) %>% 
  summarise(cases=sum(cases), deaths=sum(deaths)) %>%
  arrange(date) %>%
  mutate(CFR = ifelse(!is.na(lag(deaths, 90)) & !is.na(lag(cases, 103)),
                      (deaths - lag(deaths, 90)) / (lag(cases,13)-lag(cases,103)),
                      (deaths) / (lag(cases,13))),
         cases_2week = (cases - lag(cases, 14))/14,
         cases_2week_adj1 = cases_2week*pmax(1,(CFR/0.0138)),
         cases_2week_adj2 = cases_2week*pmax(1,(CFR/0.006)),
         deaths_2week = deaths - lag(deaths, 14)) %>%
  gather(var, val, contains("cases_2week")) %>%
  na.omit() %>%
  filter(var!="cases_2week_adj2" | date>=ymd("2020-10-01"),
         var!="cases_2week_adj1" | date<=ymd("2020-11-01"))

var_labels <- c("Reported cases",
                "Under-reporting adjusted cases: IFR = 1.38%",
                "Under-reporting adjusted cases: IFR = 0.6%")

p2 <- filter(d_plot, date>=ymd("2020-03-15")) %>%
  ggplot(aes(x=date, y=val, color=var, linetype=var)) +
  geom_line() +
  
  scale_x_date("",date_breaks = "1 month", date_labels =  "%b %Y") +
  scale_y_continuous("Case count", label=scales::comma) +
  scale_color_manual("", values = c("black", "red", "blue"),
                     labels = var_labels) +
  scale_linetype_manual("", values = c("solid", "dotted","dotted"), 
                        labels = var_labels) +
  
  #guides(color = guide_legend(ncol=1)) + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1), 
        legend.position = "bottom",
        plot.title = element_text(size=12),
        legend.margin=margin(t=-20, l=-50)) +
  guides(color=guide_legend(ncol=2)) +
  ggtitle("b) 14-day average national case count")

p2
```

## Combine plots
```{r, fig.height=7,fig.width=6}
plot_grid(p1,p2,ncol=1, rel_heights = c(3,3))
ggsave("combinned_plot.jpeg", height = 6, width = 6)
```











